apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flowman
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: smartclip/flowman
spec:
  type: etl
  owner: smartclip
  lifecycle: test
